### ISSUE TITLE
Feedback request [AWS-05 S3]

### ISSUE THREAD

**Issue by Rithmatist** [techgrounds/cloud-6-repo-Jhashikh#2]
# Feedback Request [AWS-05 S3]
Permalink naar bestand: [https://github.com/techgrounds/cloud-6-repo-Jhashikh/blob/main/02_Cloud_1/AWS-05%20S3.md]

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
Ja

- Is de samenvatting in eigen woorden geschreven?
Ja

- Mist er cruciale informatie in de samenvatting?
Nee

- Is de beschrijving duidelijk genoeg?
Ja


## Key Terms
- Missen er sleutelwoorden?
Nee

- Zijn de sleutelwoorden goed uitgelegd?
Nog geen beschrijving.

## Bronnen
- Zijn bronnen vernoemd?
Ja

- Zijn de genoemde bronnen juist?
Ja

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
Ja
- Zijn de ervaren problemen en oplossingen goed beschreven?
Ja

Deel de link van de issue met je groepsgenoten.

**Comment by Jhashikh** [comment]
> # Feedback Request [AWS-05 S3]
> Permalink naar bestand: [https://github.com/techgrounds/cloud-6-repo-Jhashikh/blob/main/02_Cloud_1/AWS-05%20S3.md]
> 
> Template voor reviewers:
> 
> ```
> ## Samenvatting
> - Beschrijft de samenvatting het onderwerp volledig genoeg?
> Ja
> 
> - Is de samenvatting in eigen woorden geschreven?
> Ja
> 
> - Mist er cruciale informatie in de samenvatting?
> Nee
> 
> - Is de beschrijving duidelijk genoeg?
> Ja
> 
> 
> ## Key Terms
> - Missen er sleutelwoorden?
> Nee
> 
> - Zijn de sleutelwoorden goed uitgelegd?
> Nog geen beschrijving.
> 
> ## Bronnen
> - Zijn bronnen vernoemd?
> Ja
> 
> - Zijn de genoemde bronnen juist?
> Ja
> 
> ## Opdracht
> (Waar van toepassing)
> - Is het resultaat correct?
> Ja
> - Zijn de ervaren problemen en oplossingen goed beschreven?
> Ja
> 
> Deel de link van de issue met je groepsgenoten.
> ```
Dank je voor feedback !
